# Generated by Django 5.2 on 2025-08-08 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('portion_type', models.CharField(default='portion', max_length=100)),
                ('min_portion_size', models.FloatField(default=1.0)),
                ('portion_increment', models.FloatField(default=1.0)),
                ('metric_type', models.CharField(default='gram', max_length=50)),
                ('metric_amount', models.FloatField(default=100.0)),
                ('main_ingredients', models.TextField(blank=True)),
                ('recipe', models.TextField(blank=True)),
                ('max_portion', models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('fat', models.FloatField()),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_total', to='mealplan.day')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('displayed_name', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('meal_time', models.TimeField(default='00:00')),
                ('consumed', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealplan.day')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portion_type', models.CharField(blank=True, max_length=50, null=True)),
                ('portion_count', models.FloatField(default=1.0)),
                ('portion_metric_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('portion_metric', models.FloatField(default=0.0)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('tarif', models.TextField(blank=True, null=True)),
                ('ana_bilesenler', models.TextField(blank=True, null=True)),
                ('consumed', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='mealplan.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='mealplan.mealplan'),
        ),
    ]
