# Generated by Django 5.2 on 2025-08-08 08:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calorie_goal', models.FloatField(blank=True, null=True)),
                ('macros_goal', models.JSONField(blank=True, null=True)),
                ('calorie_intake', models.FloatField(default=0.0)),
                ('macros_intake', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_intakes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('height_feet', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weight_lbs', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('tdee', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ideal_weight_range', models.JSONField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('ideal_body_fat_range', models.JSONField(blank=True, null=True)),
                ('calorie_deficit_surplus', models.FloatField(blank=True, null=True)),
                ('calorie_intake', models.FloatField(blank=True, null=True)),
                ('macros', models.JSONField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('sleep_duration', models.FloatField(blank=True, null=True)),
                ('remaining_hours', models.FloatField(default=0)),
                ('activity_data', models.JSONField(blank=True, null=True)),
                ('dietary_option', models.CharField(blank=True, max_length=255, null=True)),
                ('other_diet', models.CharField(blank=True, max_length=255, null=True)),
                ('main_meals', models.IntegerField(blank=True, null=True)),
                ('snack_meals', models.IntegerField(blank=True, null=True)),
                ('snack_times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None)),
                ('main_full', models.CharField(blank=True, max_length=10, null=True)),
                ('snacks_full', models.CharField(blank=True, max_length=10, null=True)),
                ('meal_times', models.JSONField(blank=True, null=True)),
                ('meal_types', models.JSONField(blank=True, null=True)),
                ('excluded_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('health_conditions', models.JSONField(blank=True, null=True)),
                ('bad_habits', models.JSONField(blank=True, null=True)),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('disliked_and_allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage_count', models.IntegerField()),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None)),
                ('stomach_status', models.CharField(blank=True, max_length=50, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_details', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck_size', models.CharField(blank=True, max_length=10, null=True)),
                ('shoulder_size', models.CharField(blank=True, max_length=10, null=True)),
                ('upperArm_size', models.CharField(blank=True, max_length=10, null=True)),
                ('chest_size', models.CharField(blank=True, max_length=10, null=True)),
                ('waist_size', models.CharField(blank=True, max_length=10, null=True)),
                ('leg_size', models.CharField(blank=True, max_length=10, null=True)),
                ('bodyFat', models.CharField(blank=True, max_length=10, null=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='survey.survey')),
            ],
        ),
    ]
